// =====================================
// ADD OR EDIT PHOTOS HERE
// The gallery ships with 20 local photo-style placeholders.
// Replace any image path with your own photo when ready.
// =====================================
const gallery = [
  { image: "images/01-her-smile.svg", title: "Her Smile", date: "September 2026", description: "A moment I never want to forget.", color: "linear-gradient(145deg,#f7c3d2,#ad687f)" },
  { image: "images/02-the-way-she-laughs.svg", title: "The Way She Laughs", date: "A favorite afternoon", description: "The sound that makes every room warmer.", color: "linear-gradient(145deg,#e9d2b4,#aa7180)" },
  { image: "images/03-softly-herself.svg", title: "Softly, Herself", date: "Collected with love", description: "Proof that the quiet moments are the most beautiful.", color: "linear-gradient(145deg,#c0d4cf,#7c9b93)" },
  ...[
    ["Golden Hour","A light worth keeping","Everything looks softer when you are near."],["A Quiet Look","The in-between","The moments you do not know I am collecting."],["Sunday Light","Slow mornings","Coffee, sunlight, and you being completely yourself."],["Her Favorite Color","A little bit of joy","A reminder that color follows you everywhere."],["Between Laughs","The best kind of pause","There is a whole story in the space between smiles."],["Blue Hour","Just before evening","The world turns blue and you make it warm."],["A Walk Together","Anywhere with you","Even the ordinary becomes somewhere worth going."],["Lavender Skies","A softer world","You make the horizon feel close enough to touch."],["Greenhouse Days","Growing things","Some beautiful things take their time."],["The Candid One","Unposed","My favorite version is always the real one."],["A Soft Morning","The first light","The day begins better when it begins with you."],["After the Rain","Fresh starts","Every ending leaves room for something lovely."],["Warm Afternoon","A golden memory","The kind of day I would gladly relive."],["Little Universe","All your details","There is an entire universe in the way you are."],["Wild & Wonderful","Entirely you","Never change the magic that makes you different."],["Sunlit Dreams","A future to imagine","The best chapters are still unwritten."],["The Last Light","Never really goodbye","Some moments stay glowing long after they end."]
  ].map(([title, date, description], index) => ({ image: `images/${String(index + 4).padStart(2, "0")}-${["golden-hour","a-quiet-look","sunday-light","her-favorite-color","between-laughs","blue-hour","a-walk-together","lavender-skies","greenhouse-days","the-candid-one","a-soft-morning","after-the-rain","warm-afternoon","little-universe","wild-and-wonderful","sunlit-dreams","the-last-light"][index]}.svg`, title, date, description, color: "linear-gradient(145deg,#e8b0bc,#775265)" }))
];

const scrapbookMemories = [
  { title: "A little sunshine", date: "the good days", caption: "You make everywhere feel like home.", color: "linear-gradient(145deg,#efd3b2,#d48b9f)", tilt: "-3deg" },
  { title: "Our kind of magic", date: "just us", caption: "Somewhere between a laugh and a look.", color: "linear-gradient(145deg,#c3d7cd,#8ca699)", tilt: "2deg" },
  { title: "Still my favorite", date: "always", caption: "I would choose this life with you again.", color: "linear-gradient(145deg,#d9c2d8,#9a748e)", tilt: "-2deg" },
  { title: "The little things", date: "every day", caption: "The details are where the love lives.", color: "linear-gradient(145deg,#f1c8c3,#c98088)", tilt: "3deg" }
];
const loveReasons = [["Your smile", "It arrives before you do, and somehow makes everything feel possible."], ["Your laugh", "The most beautiful kind of interruption. I hope I get to hear it forever."], ["Your kindness", "You notice the things other people miss. That is one of your superpowers."], ["Your little habits", "All the tiny, wonderfully-you details I would recognize anywhere."], ["The way you talk", "I could listen to your stories, your thoughts, and your sleepy voice for hours."], ["Our memories", "Every chapter with you is my favorite chapter so far."]];
const timelineMemories = [["The beginning", "Where it all started", "The first page of a story I already knew I wanted to keep."], ["The first memory", "A day worth keeping", "Some moments become landmarks. This one is one of mine."], ["More moments", "And then, more us", "The ordinary became extraordinary because I got to share it with you."], ["Today", "Still choosing you", "The best part is that our favorite memories are still ahead of us."]];

let currentPhoto = 0;
const $ = (selector) => document.querySelector(selector);
const $$ = (selector) => document.querySelectorAll(selector);
function showScreen(id) { if (id === "opening") $("#bookIntro").classList.remove("opening"); $$(".screen").forEach((screen) => screen.classList.remove("active-screen")); const screenId = id === "welcome" ? "museum" : id; const screen = $("#" + screenId) || $("#opening"); screen.classList.add("active-screen"); window.scrollTo({ top: 0, behavior: "smooth" }); if (id === "finale") createFireflies(); }
function createPetals(amount = 18) { const layer = $("#petalLayer"); for (let i = 0; i < amount; i++) { const petal = document.createElement("span"); petal.className = "petal"; petal.style.left = `${Math.random() * 100}%`; petal.style.top = `${-10 - Math.random() * 20}%`; petal.style.animationDuration = `${5 + Math.random() * 5}s`; petal.style.animationDelay = `${Math.random() * 2}s`; petal.style.transform = `rotate(${Math.random() * 180}deg)`; layer.appendChild(petal); setTimeout(() => petal.remove(), 11000); } }
function createFireflies() { const layer = $("#fireflyLayer"); if (layer.children.length) return; for (let i = 0; i < 20; i++) { const dot = document.createElement("span"); dot.className = "firefly"; dot.style.left = `${5 + Math.random() * 90}%`; dot.style.top = `${10 + Math.random() * 75}%`; dot.style.animationDelay = `${Math.random() * 2}s`; layer.appendChild(dot); } }
function renderGallery() { $("#galleryGrid").innerHTML = gallery.map((item, index) => `<article class="exhibit-card" data-photo="${index}" tabindex="0" aria-label="View ${item.title}"><div class="art-image" style="--art-bg:${item.color}"><img src="${item.image}" alt="${item.title}" loading="lazy"></div><div class="exhibit-meta"><span class="eyebrow">Exhibit ${String(index + 1).padStart(3, "0")}</span><h3>${item.title}</h3><p>${item.date}</p><p>${item.description}</p></div></article>`).join(""); $$(".exhibit-card").forEach((card) => { card.addEventListener("click", () => openViewer(Number(card.dataset.photo))); card.addEventListener("keydown", (e) => { if (e.key === "Enter" || e.key === " ") { e.preventDefault(); openViewer(Number(card.dataset.photo)); } }); }); }
function renderScrapbook() { $("#scrapbook").innerHTML = scrapbookMemories.map((item) => `<article class="polaroid" style="--tilt:${item.tilt}"><div class="art-image" style="--art-bg:${item.color}"></div><p>${item.caption}</p><small>${item.title} · ${item.date}</small></article>`).join(""); $$(".polaroid").forEach((card) => card.addEventListener("click", () => card.classList.toggle("lifted"))); }
function renderReasons() { $("#loveCards").innerHTML = loveReasons.map((item) => `<article class="love-card"><button aria-expanded="false"><span class="card-plus">+</span><h3>${item[0]}</h3><p>${item[1]}</p></button></article>`).join(""); $$(".love-card button").forEach((button) => button.addEventListener("click", () => { const card = button.parentElement; const open = card.classList.toggle("open"); button.setAttribute("aria-expanded", open); })); }
function renderTimeline() { $("#timeline").innerHTML = timelineMemories.map((item) => `<article class="timeline-item"><time>${item[0]}</time><h3>${item[1]}</h3><p>${item[2]}</p></article>`).join(""); const observer = new IntersectionObserver((entries) => entries.forEach((entry) => { if (entry.isIntersecting) entry.target.classList.add("visible"); }), { threshold: .15 }); $$(".timeline-item").forEach((item) => observer.observe(item)); }
function openViewer(index) { currentPhoto = index; updateViewer(); $("#viewer").classList.add("visible"); $("#viewer").setAttribute("aria-hidden", "false"); document.body.classList.add("no-scroll"); }
function updateViewer() { const item = gallery[currentPhoto]; $("#viewerImage").style.background = item.color; $("#viewerImage").innerHTML = `<img src="${item.image}" alt="${item.title}" style="width:100%;height:100%;object-fit:cover">`; $("#viewerExhibit").textContent = `Exhibit ${String(currentPhoto + 1).padStart(3, "0")}`; $("#viewerTitle").textContent = item.title; $("#viewerDate").textContent = item.date; $("#viewerDescription").textContent = item.description; $("#viewerCount").textContent = `${currentPhoto + 1} / ${gallery.length}`; }
function closeViewer() { $("#viewer").classList.remove("visible"); $("#viewer").setAttribute("aria-hidden", "true"); document.body.classList.remove("no-scroll"); }
$("#openBook").addEventListener("click", () => { createPetals(26); showScreen("welcome"); });
$$('[data-go]').forEach((button) => button.addEventListener("click", () => showScreen(button.dataset.go)));
$("#menuToggle").addEventListener("click", () => showScreen("contents")); $("#menuToggleContents").addEventListener("click", () => showScreen("contents")); $("#closeViewer").addEventListener("click", closeViewer); $("#viewer").addEventListener("click", (e) => { if (e.target.id === "viewer") closeViewer(); }); $("#prevPhoto").addEventListener("click", () => { currentPhoto = (currentPhoto - 1 + gallery.length) % gallery.length; updateViewer(); }); $("#nextPhoto").addEventListener("click", () => { currentPhoto = (currentPhoto + 1) % gallery.length; updateViewer(); });
$(document).addEventListener("keydown", (e) => { if (e.key === "Escape") { closeViewer(); $("#secretRoom").classList.remove("visible"); } if ($("#viewer").classList.contains("visible") && e.key === "ArrowRight") $("#nextPhoto").click(); if ($("#viewer").classList.contains("visible") && e.key === "ArrowLeft") $("#prevPhoto").click(); });
$("#unfoldLetter").addEventListener("click", (e) => { $("#letterPaper").classList.toggle("unfolded"); e.currentTarget.textContent = $("#letterPaper").classList.contains("unfolded") ? "Keep this letter close" : "Unfold the letter"; createPetals(12); }); $("#secretTrigger").addEventListener("click", () => { $("#secretRoom").classList.add("visible"); $("#secretRoom").setAttribute("aria-hidden", "false"); createPetals(16); }); $("#closeSecret").addEventListener("click", () => { $("#secretRoom").classList.remove("visible"); $("#secretRoom").setAttribute("aria-hidden", "true"); });
function createGarden() { const garden = $("#lilyGarden"); ["Secretly, I adore you.", "You are my favorite bloom.", "I would find you in every garden."].forEach((message, index) => { const flower = document.createElement("button"); flower.className = "garden-lily"; flower.style.setProperty("--x", ["10%", "42%", "74%"][index]); flower.style.setProperty("--scale", [".78", "1.12", ".9"][index]); flower.style.setProperty("--delay", `${index * -1.2}s`); flower.setAttribute("aria-label", "Discover garden message"); flower.innerHTML = `<span class="stem"></span><span class="flower lily"><i></i><i></i><i></i><i></i><i></i><b></b></span>`; flower.addEventListener("click", () => { $("#gardenMessage").textContent = message; createPetals(5); }); garden.appendChild(flower); }); }
renderGallery(); renderScrapbook(); renderReasons(); renderTimeline(); createGarden();
// The book cover is the only screen shown on first load.
showScreen("opening");
